### ISSUE TITLE
Joining Race Data with District Data 

### ISSUE THREAD

**Issue by noelgoodwin** [jonmgeiger/household-conditions#11]
Ive been messing around with the race data and managed to join the available data to the district data. I will create a branch and pull request so you all can take a look at what I did. 

One thing that came up is that the race data is short 1,404 school districts (13,314 in the district data, 11,910 in the race data). I looked into it a little bit and could not figure out why this is the case. We are going to have to make some decisions moving forward about what we want to do about this and see if we can potentially find the missing racial and ethnic district data.

**Comment by jonmgeiger** [comment]
Good work @noelgoodwin! If there's missing data, which it seems that there is, we can just leave the missing values as NA and recognize that it's just because there isn't any racial data for those particular district. 

So the district data is 13,314 rows and the race data is 11,910 rows -- when you join the data, does it join all the rows properly? In other words, do all of those 11,910 rows get matched to some row in the district data? I'm just curious if there are any that are left out due to a mismatch of names or anything of the like.

**Comment by noelgoodwin** [comment]
I am confident that all of the rows were joined properly and the only NAs correspond to those districts that the race data does not have data for. I will post the HTML and Rmd file by tonight so yall can see what I did. I was just running into issues with adding and committing them to the branch through the terminal, but I think I figured out what the issue was.

**Comment by jonmgeiger** [comment]
Wonderful! Would you make a pull request for the branch to discuss the changes?

**Comment by noelgoodwin** [comment]
Okay, I may need to ask you all a few clarifying questions about adding, committing and pushing through the terminal. I just ended up uploading the files through github and created a pull request. Let me know if that worked, but I am sure there is a better way to do it.  Anyways, take a look when you get the chance.

**Comment by jonmgeiger** [comment]
No problem at all. Uploading the files through GitHub works perfectly well; just be sure to pull the remote changes into your local repository as well (`git checkout main && git pull`).
